### ISSUE TITLE
Unable to use extension

### ISSUE THREAD

**Issue by mniewrzal** [felixfbecker/vscode-php-intellisense#1]
Hi,
I'm playing with your extension and I have problems with using it with VS Code. After cloning I executed:
- npm install
- tsc

I copied whole directory to vscode extensions directory and now when I open PHP file in developer tools console I have error message:
`
[Extension Host] Response handler 'initialize' failed with message: Cannot read property 'code' of null
`

**Comment by felixfbecker** [comment]
Please notice the big _Work in progress_ notice in the README. This extension is not published yet, but in a public repository to enable collaboration.
This extension is only a thin wrapper that spawns the https://github.com/felixfbecker/php-language-server, so bugs need to be fixed there

Feel free to contribute.

**Comment by mniewrzal** [comment]
Yes, contribution is my goal :) 

For now I'm trying to understand if my initial steps were correct and I didn't missed anything important. After I will have working version I will be able to start playing with implementation of https://github.com/felixfbecker/php-language-server

**Comment by felixfbecker** [comment]
Yes I basically create this extension already because I needed some way to test the language server. That being said though, I got initialize already working. I think you were missing some steps:
- run `composer install` to install the language server as a dependency (you need composer installed)
- run `npm run compile` to compile
This should be highlighted more in the README, I build the 3 packages in just two days and published them on GitHub as quickly as possible without writing extensible documentation :D
 
My next step is implementing documentSymbols because it is trivial with an AST. But I couldnt debug it properly, the server crashed and I couldn't get STDERR output, so I asked the VS Code folks how to do it, and got help here: https://github.com/Microsoft/vscode-languageserver-node/issues/82. I couldn't find the time to implement it yet, but that way we can get STDERR output with stacktraces. But ultimately I want all features of the language server to be verified through unit tests, because it is designed to run with many IDEs, not just VS Code.

I also used my own debug adapter https://github.com/felixfbecker/vscode-php-debug to debug the language server with success.

I am also open to adding more maintainers, would be nice if this could become a community project.

**Comment by mniewrzal** [comment]
Thanks for clarification. It looks that I was able to reach initialization step. I just thought something else should work ;) I will try add simple description to README to summarize what I did.

**Comment by felixfbecker** [comment]
https://github.com/Microsoft/vscode-languageserver-node/issues/86

**Comment by felixfbecker** [comment]
I added a solution to the problem in https://github.com/felixfbecker/php-advanced-json-rpc/commit/53808d3a53ad6fcc928bc6ddffd080b1167c71b1

`documentSymbols` is working now! 🎉
