### ISSUE TITLE
Don't suggest <?php on > character in HTML not fixed by 2.0.0 (on 2.0.1)

### ISSUE THREAD

**Issue by willpower232** [felixfbecker/vscode-php-intellisense#205]
I had the extension disabled whilst waiting for the fix to arrive, having re enabled it (having realised I had 2.0.1 now) I am still encountering the behaviour

![image](https://user-images.githubusercontent.com/1619102/33320232-711eadc6-d439-11e7-94f0-561ce33ea169.png)

I don't know if having the extension disabled meant it didn't really update but I have tried uninstalling and reinstalling the extension to no avail.

**Comment by felixfbecker** [comment]
Looks like VS Code doesn't send the new parameter yet.
@dbaeumer?

```json
{
    "id": 4,
    "method": "textDocument/completion",
    "params": {
        "textDocument": {
            "uri": "file:///Users/felix/git/felixfbecker/php-language-server/Performance.php"
        },
        "position": {
            "line": 1,
            "character": 4
        }
    },
    "jsonrpc": "2.0"
}
```

**Comment by dbaeumer** [comment]
This requires a new version of the LSP npm modules which I will publish with the next stable release of VS Code.

**Comment by aktjerry** [comment]
Sill no support (Either out of the box or via extensions) for html inside php file :( 

Come on VS !!!

**Comment by laoshaw** [comment]
looks like the intellisense is strictly based on file types, e.g. if it is a pure html, php, javascript, css it worked well, any mix of them will not(e.g. php+html mix), but these file sometimes do mix up. Can intellisense detect php/js/css/html tags and do intellisense/auto-complete based on those blocks instead of just the file name type?

really need to make sure intellisense, emmet, auto-complete work  for code that mixes html/js/css/php etc together.

**Comment by WraithKenny** [comment]
I can confirm that with VS Code 1.19 stable, and PHP IntelliSense 2.1.0, `<?php` is still being suggested on almost all keystrokes.

For example, if typing `<div></div>` the `<?php` suggestion is present after typing `d`, `i`, `v`, `>`, `<`, `d`, `i`, `v`, and `>`.

It's only not present on the very first `<` or the `/` character.
