### ISSUE TITLE
How can I specify the path for $_SERVER['DOCUMENT_ROOT']?

### ISSUE THREAD

**Issue by michaelschufi** [felixfbecker/vscode-php-intellisense#328]
There is no autocompletion for `$path = $_SERVER['DOCUMENT_ROOT']."/directory"`. Can I somehow specify the document root?

**Comment by peon501** [comment]
do it in php $_SERVER['DOCUMENT_ROOT'] = '/www';

**Comment by michaelschufi** [comment]
Will try this and report back :)

**Comment by felixfbecker** [comment]
Where exactly do you expect autocompletion?

**Comment by michaelschufi** [comment]
Path autocompletion for `$_SERVER['DOCUMENT_ROOT']."/i/would/like/suggestions/for/this/path"`. And I also think that it doesn't scan the imports because it can't resolve  `$_SERVER['DOCUMENT_ROOT']`, but I might be wrong here.

**Comment by felixfbecker** [comment]
Path autocompletion in strings is not implemented, and the language server has no knowledge of the semantics of individual keys in `$_SERVER`. There is also no autocompletion for super globals in general because variables are not added to the index for performance reasons, and `$_SERVER` is defined as a variable in https://github.com/JetBrains/phpstorm-stubs/blob/cc175cd93d541e16241848f0f0b261b90152b9e2/superglobals/_superglobals.php#L119

I'm closing this here, but you can submit a feature request for these things in https://github.com/felixfbecker/php-language-server
